### ISSUE TITLE
M2 Mac ResolvePackageNotFound: `dglteam::dgl==1.0.1`

### ISSUE THREAD

**Issue by dsm-72** [dmlc/dgl#5478]
## To Reproduce

```yml
name: dgl_env
channels:
  - pytorch
  - dglteam

dependencies:
  - python>=3.10
  - pytorch==2.0.0  
  - dglteam::dgl==1.0.1 # <--- from https://anaconda.org/dglteam/dgl
```

```sh
$ conda env create -f env.yml
```

## Expected behavior

I can install `dgl`.

## Environment
See env file above
 - OS (e.g., Linux): macOS M2 (arm) 13.2.1
