### ISSUE TITLE
Error When Building DGL from Source on Ubuntu

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#5629]
## 🐛 Bug

```
-- Build files have been written to: /home/ubuntu/5540_230425/dgl/dgl_sparse/build/2.0.0
[  7%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/elemenwise_op.cc.o
[ 15%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/matmul.cc.o
[ 23%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/matrix_ops.cc.o
[ 30%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/python_binding.cc.o
[ 38%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/reduction.cc.o
[ 46%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/sddmm.cc.o
[ 53%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/softmax.cc.o
[ 61%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/sparse_format.cc.o
[ 69%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/sparse_matrix.cc.o
[ 76%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/sparse_matrix_coalesce.cc.o
[ 84%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/spmm.cc.o
make[5]: *** No rule to make target '/opt/conda/envs/5540/lib/python3.8/site-packages/torch/lib/libc10.so', needed by 'libdgl_sparse_pytorch_2.0.0.so'.  Stop.
make[5]: *** Waiting for unfinished jobs....
[ 92%] Building CXX object CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/src/spspmm.cc.o
make[4]: *** [CMakeFiles/Makefile2:83: CMakeFiles/dgl_sparse_pytorch_2.0.0.dir/all] Error 2
make[3]: *** [Makefile:91: all] Error 2
make[2]: *** [CMakeFiles/dgl_sparse.dir/build.make:70: CMakeFiles/dgl_sparse] Error 2
make[1]: *** [CMakeFiles/Makefile2:259: CMakeFiles/dgl_sparse.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

## To Reproduce

1. `bash script/create_dev_conda_env.sh -g 11.7 -p 3.10 -t 2.0`
1. `source activate dgl-dev-gpu`
1. `bash script/build_dgl.sh -g`

based on the doc [here](https://docs.dgl.ai/install/index.html#install-from-source)

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux): Ubuntu
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.10
 - CUDA/cuDNN version (if applicable): 11.7
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
@mufeili I tried on my side and it works well. build upon latest master branch(`665c3798716b03fb34dae7045d48e85c34ea1fa9`).

according to below error message, why it's `python3.8` instead of `python3.10`. Did you create the expected conda env successfully? try with `bash script/create_dev_conda_env.sh -f -g 11.7 -p 3.10 -s -t 2.0`? just append `-f`.
```
make[5]: *** No rule to make target '/opt/conda/envs/5540/lib/python3.8/site-packages/torch/lib/libc10.so', needed by 'libdgl_sparse_pytorch_2.0.0.so'.  Stop.
```

**Comment by mufeili** [comment]
@Rhett-Ying 

I opened a new instance. After running `bash script/create_dev_conda_env.sh -f -g 11.7 -p 3.10 -s -t 2.0`

```
name: dgl-dev-gpu
dependencies:
  - python=3.10
  - pip
  - graphviz
  - pandoc
  - pygraphviz
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - cython
    - filelock
    - matplotlib
    - networkx
    - nltk
    - nose
    - numpy
    - ogb
    - pandas
    - psutil
    - pyarrow
    - pydantic
    - pytest
    - pyyaml
    - rdflib
    - requests[security]
    - scikit-learn
    - scipy
    - torch==2.0+cu117
    - torchmetrics
    - tqdm
    - boto3 # AWS SDK for python
    - sphinx==4.2.0
    - sphinx-gallery
    - sphinx_rtd_theme
    - sphinx_copybutton
    - sphinxemoji
    - nbsphinx>=0.8.11
    - nbsphinx-link>=1.3.0
    - pillow
    - seaborn
    - jupyter_http_over_ws
variables:
  DGL_HOME: /home/ubuntu/cugraph_230504/dgl
--------------------------------------------------
Create a conda enviroment with the config?
y

EnvironmentSectionNotValid: The following section on '/tmp/4c66917359cacec64598/dgl_dev.yml' is invalid and will be ignored:
 - variables
```

Did you encounter `EnvironmentSectionNotValid`? I then encountered "ERROR: Please make sure environment variable DGL_HOME is set correctly." after running `bash script/build_dgl.sh -g`.
