### ISSUE TITLE
Script to validate the COO graph topology data format.

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#5812]

**Comment by Rhett-Ying** [comment]
COO graph topology data format (part of `OnDiskDataset`) is shown below:
```
graph: # graph structure and required attributes.
  nodes:
    - type: author
      num: 1024
    - type: paper
      num: 2048
  edges:
    - type: 'author:writes:paper'
      format: csv
      path: edges/writes.csv
    - type: 'paper:cites:paper'
      format: csv
      path: edges/cites.csv
  feature_data: # edge attributed could be added here as edge feature.
    - domain: edge
      type: 'author:write:paper'
      name: prob
      format: numpy
      in_memory: true
      path: edge_data/write-prob.npy
```

Such graph will be constructed as `DGLGraph` first, then convert `CSCSamplingGraph` via [from_dglgraph()](https://github.com/dmlc/dgl/blob/cff938c6adbac28fe38ef10079a51fe3f8d97d3e/python/dgl/graphbolt/impl/csc_sampling_graph.py#L712).
